import type { Appliance, Expense, MaintenanceTask, Project, VaultDocument, Vehicle, Vendor } from "@/types/homey";

export const projects: Project[] = [
  { id: "kitchen", name: "Kitchen Remodel", area: "Kitchen", budget: 42000, spent: 28750, status: "active" },
  { id: "roof", name: "New Roof", area: "Exterior", budget: 18500, spent: 18400, status: "completed" },
  { id: "bath", name: "Primary Bath Refresh", area: "Bathroom", budget: 12000, spent: 6800, status: "active" },
];

export const expenses: Expense[] = [
  {
    id: "exp-1",
    date: "2026-06-02",
    vendor: "Atlas Stone",
    description: "Quartz slabs and delivery",
    amount: 6200,
    category: "materials",
    projectId: "kitchen",
    documentUrl: "#",
    taxDeductible: false,
  },
  {
    id: "exp-2",
    date: "2026-06-05",
    vendor: "Northline Electric",
    description: "Panel upgrade labor",
    amount: 2450,
    category: "labor",
    projectId: "kitchen",
    taxDeductible: true,
  },
  {
    id: "exp-3",
    date: "2026-06-10",
    vendor: "City Permits",
    description: "Kitchen structural permit",
    amount: 680,
    category: "permits",
    projectId: "kitchen",
    taxDeductible: true,
  },
  {
    id: "exp-4",
    date: "2026-06-12",
    vendor: "Evergreen Utilities",
    description: "Electricity bill",
    amount: 212,
    category: "utilities",
    taxDeductible: false,
  },
];

export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: "task-1",
    title: "Change HVAC filter",
    area: "Mechanical",
    notes: "Keep two 20x25x1 filters in storage and note airflow direction before removing the old filter.",
    cadence: "Every 3 months",
    dueDate: "2026-06-28",
    reminderDate: "2026-06-24",
    reminderChannel: "email",
    assignedVendorId: "vendor-hvac",
    priority: "recommended",
    status: "pending",
  },
  {
    id: "task-2",
    title: "Clean gutters",
    area: "Exterior",
    notes: "Check downspouts for clogs and photograph any loose flashing while the ladder is out.",
    cadence: "Every 6 months",
    dueDate: "2026-06-18",
    reminderDate: "2026-06-16",
    reminderChannel: "push",
    assignedVendorId: "vendor-roof",
    priority: "seasonal",
    status: "overdue",
  },
  {
    id: "task-3",
    title: "Flush water heater",
    area: "Utility",
    notes: "Attach hose before opening drain valve and listen for popping sounds after refill.",
    cadence: "Annually",
    dueDate: "2026-07-15",
    reminderDate: "2026-07-08",
    reminderChannel: "email",
    assignedVendorId: "vendor-plumbing",
    priority: "critical",
    status: "pending",
  },
];

export const appliances: Appliance[] = [
  {
    id: "appliance-1",
    name: "Main HVAC System",
    brand: "Trane",
    model: "XV20i",
    location: "Attic",
    installDate: "2018-04-12",
    expectedLifespanYears: 15,
    notes: "Ask vendor to inspect refrigerant level during fall service.",
    lastServiceDate: "2026-03-22",
    nextServiceDate: "2026-09-22",
    warrantyExpires: "2028-04-12",
    status: "monitor",
    assignedVendorId: "vendor-hvac",
  },
  {
    id: "appliance-2",
    name: "Water Heater",
    brand: "Rheem",
    model: "Performance Platinum",
    location: "Garage",
    installDate: "2020-01-08",
    expectedLifespanYears: 12,
    notes: "Flush annually and keep a copy of warranty paperwork with service records.",
    lastServiceDate: "2025-07-15",
    nextServiceDate: "2026-07-15",
    warrantyExpires: "2030-01-08",
    status: "excellent",
    assignedVendorId: "vendor-plumbing",
  },
  {
    id: "appliance-3",
    name: "Refrigerator",
    brand: "KitchenAid",
    model: "KRFC704FPS",
    location: "Kitchen",
    installDate: "2017-09-01",
    expectedLifespanYears: 13,
    notes: "Monitor temperature drift and ice maker noise before summer service.",
    lastServiceDate: "2024-11-18",
    nextServiceDate: "2026-08-01",
    warrantyExpires: "2022-09-01",
    status: "service-soon",
    assignedVendorId: "vendor-appliance",
  },
];

export const vendors: Vendor[] = [
  {
    id: "vendor-hvac",
    name: "Elena Park",
    company: "Park Climate Studio",
    type: "hvac",
    phone: "(555) 418-1204",
    email: "elena@parkclimate.example",
    address: "1208 Foundry Lane, Dallas, TX",
    rating: 4.9,
    preferred: true,
    notes: "Best for seasonal HVAC service and filter plans.",
  },
  {
    id: "vendor-plumbing",
    name: "Marcus Hill",
    company: "Hill & Copper Plumbing",
    type: "plumbing",
    phone: "(555) 613-8840",
    email: "service@hillcopper.example",
    address: "88 Waterworks Ave, Dallas, TX",
    rating: 4.8,
    preferred: true,
    notes: "Reliable for water heater flushes and emergency leak calls.",
  },
  {
    id: "vendor-roof",
    name: "Nina Rhodes",
    company: "Rhodes Exterior Co.",
    type: "roofing",
    phone: "(555) 277-3109",
    email: "nina@rhodesexterior.example",
    address: "420 Cedar Ridge Rd, Dallas, TX",
    rating: 4.7,
    preferred: false,
    notes: "Use for gutters, flashing, and roof inspection follow-ups.",
  },
  {
    id: "vendor-appliance",
    name: "Theo Grant",
    company: "Grant Appliance Care",
    type: "appliance",
    phone: "(555) 902-4581",
    email: "hello@grantappliance.example",
    address: "33 Sterling Court, Dallas, TX",
    rating: 4.6,
    preferred: true,
    notes: "Good for refrigerator, washer, dryer, and range service.",
  },
];

export const vaultDocuments: VaultDocument[] = [
  {
    id: "doc-1",
    name: "Kitchen quartz receipt.pdf",
    type: "receipt",
    url: "receipts/kitchen-quartz.pdf",
    linkedTo: "exp-1",
    uploadedAt: "2026-06-02",
  },
  {
    id: "doc-2",
    name: "HVAC warranty card.jpg",
    type: "warranty",
    url: "warranties/hvac-card.jpg",
    linkedTo: "appliance-1",
    uploadedAt: "2026-03-22",
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "vehicle-1",
    name: "Daily Driver",
    make: "Toyota",
    model: "Camry",
    year: 2021,
    mileage: 48200,
    vin: "4T1G11AK0MU000000",
    lastServiceDate: "2026-05-14",
    nextServiceDate: "2026-09-14",
    notes: "Track oil changes, tire rotations, registration renewal, brake service, and warranty documents.",
    status: "monitor",
  },
  {
    id: "vehicle-2",
    name: "Work SUV",
    make: "Honda",
    model: "Pilot",
    year: 2019,
    mileage: 73100,
    lastServiceDate: "2026-04-02",
    nextServiceDate: "2026-07-02",
    notes: "Front brake inspection due soon. Keep repair invoices for resale and warranty history.",
    status: "service-soon",
  },
];

export const monthlySpend = [
  { month: "Jan", utilities: 420, upgrades: 1800 },
  { month: "Feb", utilities: 398, upgrades: 2400 },
  { month: "Mar", utilities: 455, upgrades: 3800 },
  { month: "Apr", utilities: 430, upgrades: 5200 },
  { month: "May", utilities: 510, upgrades: 8200 },
  { month: "Jun", utilities: 472, upgrades: 9330 },
];
