const getElizaBaseUrl = () => (process.env.REACT_APP_ELIZAOS_URL || "").replace(/\/$/, "");

export const buildLocalCoachResponse = (connection, localAdvice) => ({
  recommendation: `${localAdvice.recommendation} Keep the next move specific, kind, and easy to decline.`,
  message: localAdvice.message,
  dateIdea: localAdvice.dateIdea,
  topics: localAdvice.topics,
  safety:
    "Keep first meetings public, share the plan with someone you trust, and do not ignore pressure or discomfort.",
});

export const requestElizaAdvice = async (connection, localAdvice) => {
  const baseUrl = getElizaBaseUrl();

  if (!baseUrl) {
    return {
      source: "local",
      status: "Local coach active. Add REACT_APP_ELIZAOS_URL to connect the ElizaOS agent.",
      ...buildLocalCoachResponse(connection, localAdvice),
    };
  }

  const response = await fetch(`${baseUrl}/connection-advice`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      connection,
      localAdvice,
    }),
  });

  if (!response.ok) {
    throw new Error(`ElizaOS request failed with status ${response.status}`);
  }

  const data = await response.json();

  return {
    source: "elizaos",
    status: "Generated by ConnectionCoach.",
    recommendation: data.recommendation || localAdvice.recommendation,
    message: data.message || localAdvice.message,
    dateIdea: data.dateIdea || localAdvice.dateIdea,
    topics: Array.isArray(data.topics) ? data.topics : localAdvice.topics,
    safety: data.safety || buildLocalCoachResponse(connection, localAdvice).safety,
  };
};
